### ISSUE TITLE
sxyprn.com popups [Entity sxyprn.* not supported]

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uBOL-issues#10]
Visit this website: [NSFW]: `https://www.sxyprn.com/`
Click on anywhere on the page or a video and a random ad related website opens in a new tab.
uBOL version: uBOLite_0.1.22.10166 from GitHub 
Browser: Chrome 
"The issue was brought up by a member in the malwaretips forum"

**Comment by mapx-** [comment]
That's because the current filter in uBO filters lists is not supported by mv3

`*$frame,script,3p,denyallow=google.com|googleapis.com|gstatic.com|hcaptcha.com|recaptcha.net,domain=sxyprn.*`

more specifically: `Entity sxyprn.* not supported`

**Comment by SeriousHoax** [comment]
> That's because the current filter in `uBO filters` list is not supported by mv3
> 
> `*$frame,script,3p,denyallow=google.com|googleapis.com|gstatic.com|hcaptcha.com|recaptcha.net,domain=sxyprn.*`
> 
> more specifically: `Entity sxyprn.* not supported`

Ow, I see. Will it be possible to add the MV3 compatible filter in the future to prevent this from happening?

**Comment by mapx-** [comment]
I added the filter in the special uBOL list but ... will be effective only after a new build will land in the google store.

**Comment by okiehsch** [comment]
Add `sxyprn.net` too, it's the same site.

**Comment by SeriousHoax** [comment]
> I added the filter in the special uBOL list but ... will be effective only after a new build of uBOL will land in the google store.

Nice, thanks. If you consider this solved, then you may close the issue.

**Comment by mapx-** [comment]
I tested the filter (unpacked uBOL) converting the "classic" one in the mv3-json  equivalent (and appending it to default.json file)

@gorhill we'd need a tool / script to do it faster (sure, having the dynamic "my filters" would be a huge help)

```
    {
    "action":
        {
        "type": "block"
        },
    "condition":
        {
        "domainType": "thirdParty",
        "excludedRequestDomains":
            [
            "google.com",
            "googleapis.com",
            "gstatic.com",
            "hcaptcha.com",
            "recaptcha.net"
            ],
        "initiatorDomains":
            [
            "sxyprn.com",
            "sxyprn.net"
            ],
        "resourceTypes":
            [
            "script"
            ]
        },
    "id": 20057
    }
```

**Comment by Yuki2718** [comment]
This is serious, we will need a lot more filters for uBOL. Coincidently Brave does too: https://github.com/brave/adblock-lists/pulls?q=is%3Apr+wildcard+is%3Aclosed+label%3AuBO-domain-wildcard (Although IIRC Brave now supports entity filter in cosmetic filters.)

**Comment by AntiAdvert** [comment]
popup on `NSFW: sxyprn dot com`

**Comment by Yuki2718** [comment]
I don't

**Comment by AntiAdvert** [comment]
If it's an adserver, could it be fixed in EasyList?

Also, I believe there was a popup on `daftsex dot com` even with uBO, could a `denyallow` filter be used for that site?

**Comment by Yuki2718** [comment]
> For uBOL, this should do

Yeah, so I wonder why not.

**Comment by AntiAdvert** [comment]
is there a deleted comment? 
https://user-images.githubusercontent.com/117537631/200177718-fb2eec5e-eab9-4484-84c5-1c321378c6a3.png

**Comment by gorhill** [comment]
I see three scriptlet injection filters for `daftsex.com`:

    daftsex.com##+js(aopr, TextDecoder)
    daftsex.com##+js(aopr, AaDetector)
    daftsex.com##+js(set, extEnabled, 0)

However when debugging, I see that the `TextDecoder` one is not nijected while it is supportd by uBOL. I need to investigate why it's not enforced in uBOL.

**Comment by Yuki2718** [comment]
> What I suggested was already present in 

Despite the denyallow rule, `ocwagmlizb.com` is unblocked on `sxyprn.com` with uBOL 0.1.22.10295

**Comment by gorhill** [comment]
@Yuki2718 Because the filter is entity-based, this makes it incompatible with DNR:

    *$frame,script,3p,denyallow=google.com|googleapis.com|gstatic.com|hcaptcha.com|recaptcha.net,domain=sxyprn.*

**Comment by Yuki2718** [comment]
uBOL filters has `*$frame,script,3p,denyallow=google.com|googleapis.com|gstatic.com|hcaptcha.com|recaptcha.net,domain=sxyprn.com|sxyprn.net`

**Comment by AntiAdvert** [comment]
> *$frame,script,3p,denyallow=google.com|googleapis.com|gstatic.com|hcaptcha.com|recaptcha.net,domain=sxyprn.com|sxyprn.net

maybe it would work better if `frame,script` was removed and more woul be added to `denyallow`

**Comment by gorhill** [comment]
I don't see any `sxyprn` in the main ruleset, so that `denyallow` filter never made it into uBOL. On my side in uBO, I see the filter I copy-pasted above, the `domain=sxyprn.*` one.

**Comment by AntiAdvert** [comment]
What's the best way to update lists in uBOL?

**Comment by iam-py-test** [comment]
> What's the best way to update lists in uBOL?

I don't think there is one, you have to wait for a new extension version & then update the extension. (or use the unpacked version)

**Comment by gorhill** [comment]
Was `daftsex.com##+js(aopr, TextDecoder)` added recently? I see that it's now properly injected in my local build of uBOL.

**Comment by gorhill** [comment]
Yes, fixed with <https://github.com/gorhill/uBlock/commit/6574ede152ac571587454167ded34a1877f73c09>.

**Comment by stephenhawk8054** [comment]
It's already in the list

https://github.com/uBlockOrigin/uAssets/blob/1d40604180a77ea9ca85151e59b416b1acd5c241/filters/filters-general.txt#L741

**Comment by stephenhawk8054** [comment]
Ah yeah, forgot I was testing uBO dev build. That filter will work in next uBOL version though.
