### ISSUE TITLE
[Chrome Incognito] Opening settings in new page doesn't work as expected

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uBOL-issues#13]
https://user-images.githubusercontent.com/117537631/200176251-c7611569-957d-4110-98a6-f9bd200bb02e.mp4

I'm not sure if this due to any speculated limitations of MV3, and if it is so, sorry for the creation of this issue.

**Comment by gorhill** [comment]
Unable to reproduce. You are not providing all detailed steps for me to reproduce -- every single detail is important otherwise the issue can't be addressed until I can reproduce.

**Comment by AntiAdvert** [comment]
1. Open an incongnito window
2. Click uBOL's shield icon (or its section if it's unpinned)
3. Attempt to open uBOL's settings either by:
- Right clicking the gear icon, followed by an attempt to open the settings to open the settings dashboard in a new tab
![image](https://user-images.githubusercontent.com/117537631/200177075-b37f390b-0ed5-4c4e-b877-937ff0c1586b.png)
- Or by pressing on the mouse's scroll wheel
4. 
![image](https://user-images.githubusercontent.com/117537631/200177261-e6fb7afa-ebb9-49f0-8de3-750aa696f8c7.png)

**Comment by krystian3w** [comment]
Maybe API limitation to needed report https://crbug.com

**Comment by gorhill** [comment]
When I click gears icon, the options page opens in a non-incognito browser, I can't reproduce the options page not opening.

**Comment by AntiAdvert** [comment]
> When I click gears icon, the options page opens in a non-incognito browser, I can't reproduce the options page not opening.

Did you try opening the settings in a new tab?

**Comment by krystian3w** [comment]
On Windows 10 & 11 in Incognito window no allowed is open addon settings via:

- bookmarks url
- direct write/paste url
- middle click
- drop down menu "open in new private tab"

Same limitation has AdGuard and "Enhancer for YouTube™"/

**Comment by gorhill** [comment]
I can't open in a new tab when in incognito mode. But it's the browser itself preventing this, it looks like the browser will only open the options page in a non-incognito tab, and if trying to force it to open in an incognito tab, it will refuse.

**Comment by gorhill** [comment]
I can make the options page open in an incognito tab when using `"incognito": "split"` in manifest, but this means you can end up with two options pages opened, one in normal mode, the other in incognito mode. Not sure this is an improvement given how confusing this can be and maybe other unforeseeable side effects. I think to just stick to open the options page by clicking the gear icon with the default mouse button is acceptable.

**Comment by AntiAdvert** [comment]
> Not sure this is an improvement given how confusing this can be and maybe other unforeseeable side effects

Isn't that kind of a thing with uBO on chromium?

**Comment by gorhill** [comment]
Yes and I am not fond of this, but I do not have choice with uBO because otherwise not using `split` causes uBO to not be able to open the document-blocked page, it causes an error as the one seen here when trying to open the options page. With uBOL, it's not really a showstopper issue.

**Comment by gorhill** [comment]
The _gears_ icon is no longer a `a` (link) element, so it's no longer possible to right-click it and select _Open link in a new tab_.
