### ISSUE TITLE
Request to add more privacy lists to those available

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uBOL-issues#16]
This request to add some privacy-specific lists,also present in Filterlists,to the lists currently present in the extension:

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US%2Bmost_used_ad_and_tracking_networks.txt

**Comment by gorhill** [comment]
Declined. At this point I will stick to lists already offered in uBO sinc ewe know what to expect from these.

**Comment by gwarser** [comment]
- `clear_urls_uboified.txt` completely experimental and not recommended.
- `LegitimateURLShortener.txt` good but rather hardcore - should be enabled after researching it a bit (knowing the support page at least)
- `EU_US%2Bmost_used_ad_and_tracking_networks.txt` first time hear about it.

**Comment by SampeiNihira** [comment]
Simplicity, does not mean lack of minimal functionality in comparison with other adblockers with MV3 rules.
Just to cite an example,ABP will offer users the choice of 10 lists out of a total of 50 lists:

https://blog.adblockplus.org/blog/how-adblock-plus-is-getting-ready-for-manifest-v3

However, again, I respect your choices and will never bother you again with similar problems.
