### ISSUE TITLE
Request to add "My Filters" functionality.

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uBOL-issues#17]
This feature would be greatly appreciated.
Also restricted to a limited number of rules.
Thank you for your attention and good work.

**Comment by gorhill** [comment]
Declined. I will be very strict with enforcing the "Lite" in "uBlock Origin Lite". uBO is still there for whoever want more than what uBO Lite offers. Keep in mind that to keep burdening uBO Lite with more and more demand is asking uBO Lite project to end up as uMatrix did.

**Comment by SampeiNihira** [comment]
I respect your decision.
I will never bother you again by opening other issues similar to this one.

**Comment by MeechaPooch** [comment]
once devin ai is public we can all say yes :P
