### ISSUE TITLE
blog.jp issues

### ISSUE THREAD

**Issue by pikesaury** [uBlockOrigin/uBOL-issues#18]

**Comment by SampeiNihira** [comment]
@pikesaury

While waiting for the required functionality,which would not be a priority,you can install another extension always with MV3 rules:

https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/releases/tag/v1.1.0

The extension uses roughly 1,500 rules of the 30,000 guaranteed for each extension.

**Comment by pikesaury** [comment]
@SampeiNihira
Sorry for the late reply.
It is a very good plugin, but I have decided to use AdGuard AdBlocker MV3 Experimental for a while.
