### ISSUE TITLE
Vivaldi and Vivaldi Portable browsers crash upon clicking on About in uBO Lite

### ISSUE THREAD

**Issue by midimusicman79** [uBlockOrigin/uBOL-issues#19]
Browsers: Vivaldi and Vivaldi Portable v.5.6.2867.40 (Chromium v.108.0.5359.105)
OS: Microsoft Windows 10 Professional 64-bit v.22H2 (OS build 19045.2311)
UBO Lite v.0.1.22.11296

Upon clicking on About in uBO Lite, these browsers immediately and automatically crash without any error message(s).

But this issue is not present in Google Chrome or other Chromium-based browsers.

Could you please fix this issue?

Thank you very much in advance!

**Comment by mapx-** [comment]
Did you disable vivaldi builtin blocker ?

**Comment by midimusicman79** [comment]
Thank you!

No, but I have done that now, however, the issue persists.

**Comment by mapx-** [comment]
Well, I was able to reproduce, I disabled the filters here:
![image](https://user-images.githubusercontent.com/10303732/206872594-f9d11e19-0948-4fab-9a95-92134ebbd98f.png)

and didn't crash anymore.
Then I enabled again, crash again.

So, after enabling Ads, go in other tab (google for example), refresh it, go back to settings and try now "about". It worked for me after switching Ads on / off twice.

**Comment by mapx-** [comment]
You could also try switching from basic to complete and back

**Comment by mapx-** [comment]
@gorhill 
Now - no crash on my side - however I get this in console (file missing)

![image](https://user-images.githubusercontent.com/10303732/206872796-c7347653-1bd2-4b18-be2c-404ba617081f.png)

**Comment by gorhill** [comment]
uBOL is JS/HTML/CSS, it's not supposed to crash the browser. If the browser crash, report to browser devs.
