### ISSUE TITLE
Remove AdGuard CNAME-Cloaked Trackers

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uBOL-issues#21]
They're periodically imported to EP with problematic domain removed, so it's no need, and even worse does casue trouble. I could reproduce part of trouble in https://github.com/AdguardTeam/cname-trackers/issues/8#issuecomment-824651314 if the list is enabled on uBOL. This is their stance about the list: https://github.com/AdguardTeam/cname-trackers/issues/8#issuecomment-824698453.

**Comment by SampeiNihira** [comment]
The "**AdGuard CNAME disguised trackers list**" (it would probably be better to rename this list) contains more CNAME rules than "EP" and also than "AdGuard Tracking Protection filter."
Even if it breaks a few websites the protection from CNAME trackers is greater

**Comment by SampeiNihira** [comment]
- Would it be problematic for a user who does not want broken websites to **deselect** the list?

- Or select the "**no filtering**" option for the specific broken website?

Personally I don't care that much,but if asked I would consider removing the list unnecessary.

**Comment by Yuki2718** [comment]
> it would probably be better to rename this list

Yes, as "ANY cname of some tracking vendor's domain list regardless if tracker or not". It has some additional click-through tracker which few user would ever come across while the rest does not enhance privacy, more of a false sense of privacy.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/commit/65a3cddf9509a190c97a056457e1e94c1290a8d6

**Comment by gorhill** [comment]
The list is gone in 0.1.22.12266.

**Comment by SampeiNihira** [comment]
https://github.com/AdguardTeam/cname-trackers/issues/75

I ask if it is possible to reconsider this choice considering the news listed by Shavaleleka.

**Comment by Yuki2718** [comment]
Any decision will be made by actual benefit to all user based on real-world usage than to some geeks' satisfaction. The major reason of 
> contains more CNAME rules

 is exactly https://github.com/AdguardTeam/cname-trackers/issues/51 , there's little difference in *actual* tracking protection in which some user would never get any benefit (the biggest factor other than browsing habit here is region). Besides, removing microsites/landing pages/clickthrough domains does not completely solve the afformentioned or known problems as some breakage don't fall into any of the catogory.

**Comment by SampeiNihira** [comment]
The CNAME combined_disguised_ads.txt list has only 23202 total rules:

https://github.com/AdguardTeam/cname-trackers

**Comment by Yuki2718** [comment]
@SampeiNihira If you're not aware, disguised_ads is not included in EP, EL, or AGTPF. It's included only in AG Base. This does not mean uBO with standard settings is not protected against them - we have many generic and regex rules to catch them; however, none of these is perfect and even disguised_ads list occasionally fails as these cname adservers are rapid changer (can't find an example issue, GH search is tr**h). Perfect protection comes only by DNS (uBO on Firefox, AG apps with DNS filtering, or other DNS solution). But a question is who needs that - **un**like cname tracker which is impossible not to encounter, cname adservers are almost exclusively used on pirate sites, dubious streaming or porn sites, and some link shortner.

**Comment by SampeiNihira** [comment]
I understand your point of view Yuki.
And excuse me for these interventions of mine that may annoy.
I only wish to bring to your attention a more general point of view that is shareable with a wide audience of your possible users.

Conclusion.
My only example is due to the fact that with UBO Lite you cannot select the basic AG filter list.
With this intervention,I conclude.
You of course act as you see fit.
Good evening to you all

**Comment by Yuki2718** [comment]
Well, I guessed misunderstanding so added explanation, that's all - if I ever feel annoying, I'm free to say so or ignore. Sorry if my comments sounded authoritative.
