### ISSUE TITLE
Quickbooks Login Blocked

### ISSUE THREAD

**Issue by K1ngw1ng** [uBlockOrigin/uBOL-issues#30]
Quickbooks login fails to load when extension is enabled,Test on Chrome on Mac

**Comment by iam-py-test** [comment]
This looks to be caused by blocking `https://logging.api.intuit.com/v2/log/message`

**Comment by gorhill** [comment]
I suspect it's rather caused by `||intuitcdn.net/*/intuit-analytics.$script,3p,redirect-rule=noop.js` not being present in uBO lite -- `redirect-rule` can't be converted to MV3 (redirect` can though).

**Comment by gorhill** [comment]
This will be fixed in next release of uBO Lite.
