### ISSUE TITLE
The redirect rule does not work as expected

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uBOL-issues#31]
uBlock Origin Lite 0.1.23.3038 + RU AdList
Google Chrome 110.0.5481.177

Example: `https://www.rambler.ru/`

When applying the rule: `||zoomdecorate.rambler.ru^$script,redirect=noopjs,domain=rambler.ru` the site breaks because a block is performed instead of a redirect.

I'm not sure if the problem only affects this site, perhaps the redirect is just not implemented in the way it was planned yet.

**Comment by gorhill** [comment]
I see those two DNR rules:

Block rule:

```json
 {
  "action": {
   "type": "block"
  },
  "condition": {
   "initiatorDomains": [
    "afisha.ru",
    "autorambler.ru",
    "championat.com",
    "eda.ru",
    "gazeta.ru",
    "lenta.ru",
    "letidor.ru",
    "moslenta.ru",
    "motor.ru",
    "passion.ru",
    "quto.ru",
    "rambler.ru",
    "wmj.ru"
   ],
   "requestDomains": [
    "zoomdecorate.rambler.ru"
   ],
   "resourceTypes": [
    "script"
   ]
  },
  "id": 4331
 },
```

Redirect rule:

```json
 {
  "action": {
   "redirect": {
    "extensionPath": "/web_accessible_resources/noop.js"
   },
   "type": "redirect"
  },
  "condition": {
   "initiatorDomains": [
    "afisha.ru",
    "autorambler.ru",
    "championat.com",
    "eda.ru",
    "gazeta.ru",
    "lenta.ru",
    "letidor.ru",
    "moslenta.ru",
    "motor.ru",
    "passion.ru",
    "quto.ru",
    "rambler.ru",
    "wmj.ru"
   ],
   "requestDomains": [
    "zoomdecorate.rambler.ru"
   ],
   "resourceTypes": [
    "script"
   ]
  },
  "id": 5851,
  "priority": 2
 },
```

The `redirect` rule has `priority: 2`, meaning it should win over the `block` rule, for which the priority is implicitly `1`, as per [DNR documentation](https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/#type-Rule).

So I don't understand what is the issue.

**Comment by gorhill** [comment]
Actually the Network pane says the error is `ERR_UNSAFE_REDIRECT`.

**Comment by dimisa-RUAdList** [comment]
And if use `important` - it will not help?

**Comment by gorhill** [comment]
It won't make a difference, the browser API refuses to redirect, I don't know why. For now best to fix using an exception:

    !#if !env_mv3
    ||zoomdecorate.rambler.ru^$script,redirect=noopjs,domain=rambler.ru
    !#endif

**Comment by gorhill** [comment]
Just to confirm, I do see the redirect DNR rules working for example on `https://arstechnica.com/`, so there is something about `https://www.rambler.ru/` that breaks redirect DNR rules.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/5b9e42dc87cd50069a43a189064992f28e653833

Is this how it would be right?

**Comment by gorhill** [comment]
Yes, but do you really need to also remove the `u##+js(...)` filter too?

**Comment by dimisa-RUAdList** [comment]
Why? `##+js(abort-current-inline-script, dispatchEvent, zoomdecorate)` should work in mv3 instead of the disabled redirector rule and prevent requests to `zoomdecorate.rambler.ru`

**Comment by gorhill** [comment]
Never mind, I misread the `!#if mv3` directive as `!#if !mv3`. All good.
