### ISSUE TITLE
Translation error for RO

### ISSUE THREAD

**Issue by dfunkt** [uBlockOrigin/uBOL-issues#34]
The extension name in Romanian is wrong, it says ubock instead of uBlock. I tried to change it on Crowdin but this particular string doesn't appear for me.

https://github.com/gorhill/uBlock/blob/master/platform/mv3/extension/_locales/ro/messages.json#L3

**Comment by krystian3w** [comment]
Fixed: https://github.com/gorhill/uBlock/commit/c3df4ced0a833e484e633275206589b369147c87#diff-68b233e6a9b9e8f04ebed915734309e0f53ca5a37fd693f8c7ac83fb34d2856aL3

https://github.com/gorhill/uBlock/blob/c3df4ced0a833e484e633275206589b369147c87/platform/mv3/extension/_locales/ro/messages.json#L3
