### ISSUE TITLE
Can't disable filtering on Slice New Tab Page

### ISSUE THREAD

**Issue by bgiesing** [uBlockOrigin/uBOL-issues#42]
I use a browser extension that gives you a few cents every month for showing ads on your new tab page, previously they had the tab page on `https://sli.ce.it/tab` and I could disable filtering just fine like any other website.

They just pushed an update that changes the URL to `https://tab.sli.ce.it/` and now I can't disable filtering somehow, when I click the "No Filtering" button, it just instantly flips back to my default of Optimal which I've never seen happen on any other site. I can switch to Basic just fine but it doesn't stick if you choose off.

Below is a GIF showing what's happening on the new page vs the old page (and well every other website)
![uteS61bN2J](https://github.com/uBlockOrigin/uBOL-issues/assets/7895463/56dfc3e6-6fce-483d-9d7a-f23dab616ebd)

Browser: Edge Dev 115.0.1843.0
OS: Windows 11 22H2 25357.1

**Comment by gorhill** [comment]
I can reproduce.

For now, the workaround is to go to `https://sli.ce.it/tab` and reset the blocking mode to whatever the default mode is on your side, then go to `https://tab.sli.ce.it/` and it should work fine now.

**Comment by bgiesing** [comment]
Yep that seems to have worked for now.

**Comment by gorhill** [comment]
Fixed in newly released 0.1.23.5226.
