### ISSUE TITLE
Rethinking publication in AMO with a 114 version requirement?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uBOL-issues#45]
> At the moment it is not possible to sign an extension for Firefox Nightly because AMO [refuses to sign when minimum version is 113a1](https://addons.mozilla.org/api/v5/applications/firefox/). As soon as AMO allows, a signed version of the extension will be published.

As far as I'm concerned, there `113a1` won't appear there anymore if you don't ask for it on bugzilla, because they added other newer ones and `113a1` seems to have been forgotten:

> ![obraz](https://github.com/uBlockOrigin/uBOL-issues/assets/35370833/af64fe35-c3a4-425d-86f6-ea0e5d050d8b)

```json
,"109.*","110.0","110.*","111.0","111.*","112.0","112.*","113.0","113.*","114.0","114.*","115.0","115.*","*"]}
```
```js
//                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by gorhill** [comment]
There are still some issues with cosmetic filtering specific to Firefox (not fully reliable), and scriplet filtering still doesn't work since Firefox API does not yet support `MAIN` world. I prefer to delay publishing AMO, this would lead to too many unmet expectations.

**Comment by krystian3w** [comment]
This could update the point into releases to a more understandable "all bugs in their API will be fixed" for the newbie.
