### ISSUE TITLE
hdrezka.ag

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBOL-issues#47]
`https://hdrezka.ag/films/horror/58348-pchely-ubiycy-1995.html`

Why this rule doesn't work in uBOL?

`##body.has-brand .b-content__main > div[style^="height: 250px; overflow: hidden;"]` ~> **RU AdList**

<details>
<summary>Screen</summary>

![2023-06-14_111135](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/5bf00ab6-7fa6-4db6-9db3-81ae6f2bced1)
![2023-06-14_111135](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/f05a2cad-3ac9-4ad5-b35e-08ff673b728e)
</details>

**Comment by gorhill** [comment]
I cannot find that element in the DOM. Does this require logging in?

**Comment by dportvine** [comment]
> Does this require logging in?

No, try using VPN Russia or Ukraine

@dimisa-RUAdList
Can you reproduce it in uBOL?

**Comment by dimisa-RUAdList** [comment]
Yes, I see this issue. If it can't be solved at the extension level, I can change the rule (and the like) to: `ag,buzz,by,city,club,co,com,in,ink,loan,me,name,net,org,rest,run,sh,today,tv,vip,website,win##body.has-brand .b-content__main > div[style^="height: 250px; overflow: hidden;"]`

**Comment by gorhill** [comment]
I found that the filter is rejected at compile time, I need to fix this.

**Comment by gorhill** [comment]
This case could trivially be fixed, but just a note for myself and possibly future issues being filed is that highly generic cosmetic filters are discarded by uBOL at the moment. These have to be unconditionally injected in all web pages, so I haven't decided if it's something uBOL should do in _Complete_ mode.

**Comment by dimisa-RUAdList** [comment]
In this case, I used the generic rule due to the fact that this online-cinema has a huge number of mirrors. And if I'm not mistaken, they have a service that allows any authorized user to create a personal mirror. Thus, the number of mirrors is simply incalculable.

**Comment by gorhill** [comment]
The current case does not involve a "highly generic cosmetic filter", so I could fix this in uBOL.
