### ISSUE TITLE
Powerapps getting blocked

### ISSUE THREAD

**Issue by Gopi1991R** [uBlockOrigin/uBOL-issues#49]
Hi Team ,
             Please find attached the logs for PowerApps blocked by uBlock. Please help to bypass "https://apps.powerapps.com/play/*" to use PowerApps from Microsoft products.

Screenshot for the error
 
![2023-06-14_17-04-49](https://github.com/uBlockOrigin/uBOL-issues/assets/129826408/8c95c9cc-7e56-485b-b79c-fab40a79cfb5)
[powerapps.txt](https://github.com/uBlockOrigin/uBOL-issues/files/11745252/powerapps.txt)
[apps.powerapps.com_Archive 23-06-14 02-09-23 (002).har.txt](https://github.com/uBlockOrigin/uBOL-issues/files/11745255/apps.powerapps.com_Archive.23-06-14.02-09-23.002.har.txt)

**Comment by mapx-** [comment]
@Gopi1991R it's better now, but:

- provide the explanation on **what is broken and HOW to reproduce it**.
- **what actions have to do in that powerapps page ?** 

**Comment directly here, do not send unreadable emails.**

**Comment by mapx-** [comment]
probably an exception like this is required:

`@@||browser.pipe.aria.microsoft.com/Collector/$xhr,domain=powerapps.com`

but you have to test it uBO not uBOL

and provide the info above

**Comment by Gopi1991R** [comment]
Hi Team,

                 For this required for specific path or common to PowerApps as per my company domain?

Please find the domain path
                              https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.9&content-encoding=base64&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238,5c3a61f48d7c4522912765ae7465ab5c-8472b9b6-f99b-4baf-8db9-f97fcc0ca092-7243&client-time-epoch-millis=1686740995234

Thanks
Gopinath R

**Comment by mapx-** [comment]
> what is broken and HOW to reproduce it

**@Gopi1991R  I want only this information, do you understand me ?
What functionality is broken ? Differences between using powerapps with / without uBO / uBOL ?**

**Comment by Gopi1991R** [comment]
Let me close now. I will reopen once all the details are gathered. Also, in the meantime, discussing the issue with Microsoft's product team

**Comment by Gopi1991R** [comment]
Let me close now. I will reopen once all the details are gathered. Also, in the meantime, discussing the issue with Microsoft's product team
