### ISSUE TITLE
Add a list for cookies warnings

### ISSUE THREAD

**Issue by SampeiNihira** [uBlockOrigin/uBOL-issues#5]
UBO Lite v.0.1.22.9305
Extended filtering enabled.

Please add rules for cookies warnings.
The list "AdGuard Cookie Notices filter"

`https://filters.adtidy.org/windows/filters/18.txt`

at least in UBO, resolves almost all the notices attached in the screenshots.
TH.
![1](https://user-images.githubusercontent.com/44166263/193321598-90a1047f-4477-4c09-b221-b1e24a596001.jpg)
![2](https://user-images.githubusercontent.com/44166263/193321631-b9ecc947-c7ee-47df-91a4-8c676537ab94.jpg)
![3](https://user-images.githubusercontent.com/44166263/193321648-209f93ce-1e0c-458b-95bc-fbb7f85331bd.jpg)
![4](https://user-images.githubusercontent.com/44166263/193321680-fead340d-eae6-4030-bbe9-fa35020c37c7.jpg)

**Comment by troysjanda** [comment]
Also the list for I dont care about cookies, Easylist cookie, and also a few of the lists for social stuff.

**Comment by gorhill** [comment]
> The list "AdGuard Cookie Notices filter"

I would probably go with EasyList Cookie which is already a stock filter list in uBO.

However at this point uBOL does not supports generic cosmetic filtering, and EasyList Cookie has nearly 17K of generic cosmetic filters, so it won't be very useful until (and if) generic cosmetic filters are supported.

> Also the list for

MV3 limits the number of enabled rulesets at 10, so including more than one lists for cookies won't work. For those who want more than what can be achieved with the MV3 limitations, uBOL is not for them.

**Comment by SampeiNihira** [comment]
EasyList Cookie is an obsolete list (2020) and does not update.
Even in UBO it would have to be replaced with the list I recommended.

![6](https://user-images.githubusercontent.com/44166263/193341555-a6dd65a0-809f-421b-927a-8f53126ea2db.jpg)

**Comment by gorhill** [comment]
It certainly is not obsolete, it last updated today:

>     Updated: 2022-09-30 19:20 UTC

EasyList server has had issue recently, maybe these are still is ongoing. Try downloading the one at <https://secure.fanboy.co.nz/>.

**Comment by SampeiNihira** [comment]
You are right,there is a heavy storm here,I had network problems.
ELC (41146).
But it has more rules than AG (22309).

**Comment by Yuki2718** [comment]
> MV3 limits the number of enabled rulesets at 10, so including more than one list for cookies won't work. 

That is for enabled rulesets so as long as there's a room to the total rulesets limit (50), including AG Cookie and let user to choose which one to enable should be possible. But I guess you wanna realize the idea of simple filter selection discussed in past e.g. just choosing "Cookie" category automatically enables ELC.

**Comment by krystian3w** [comment]
hopefully activating the community-wide list by default will force a better fix for bugged heritage filters.

**Comment by krystian3w** [comment]
hopefully activating the community-wide list by default will force a better fix for bugged heritage filters.

**Comment by Gandalf-The-Wise** [comment]
Any news on this issue, will a list be implemented?

**Comment by gorhill** [comment]
Declining for now, I may re-evaluate in the future as the MV3 API mature. Making Easylist Cookies available led to undue delay when changing filtering mode, due to some unidentified performance issue with `[scripting.registerContentScripts()`](https://developer.chrome.com/docs/extensions/reference/scripting/#method-registerContentScripts) (as can be seen in the browser's task manager).

Probably best for now to rely on a specialized extension for the task of dealing with cookie warnings.

**Comment by dportvine** [comment]
It doesn't work for me `censor.net###usage_notice` ~> **EasyList – Cookie Notices**

<details>
<summary>Screen</summary>

![2023-06-04_093422](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/611c5dbe-d442-485d-8ff0-e68e37350bb5)
![2023-06-04_093458](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/6616ba97-6e7a-4eed-b271-8a144810301c)
![2023-06-04_093841](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/7bf55584-d592-4fda-b34d-07844a93dae4)
</details>

**Comment by gorhill** [comment]
The element has an inline style, though I am pretty sure this was working before, it seems Chromium may have changed its implementation of CSS layer such that inline style is back to having precedence to the CSS layer injected by uBO.

The proper solution for uBO (to stay entirely declarative) is [Proposal: Declarative Cosmetic Rules}(https://github.com/w3c/webextensions/issues/362).

**Comment by SampeiNihira** [comment]
I note that this functionality has been implemented.
My compliments.

It is still required to consider user input of custom rules (consent/block) that can solve some problematic websites.

Which are **not solved only by the default filter lists.**
I can give examples,even if they are adult content websites.

**Comment by gorhill** [comment]
> user input of custom rules

That won't be part of uBO Lite, otherwise it's not going to be _Lite_ anymore. For this sort of functionality, that is uBO itself. There is no point using the _Lite_ version if you want everything uBO itself has.

**Comment by SampeiNihira** [comment]
Is it possible to at least consider some exceptions to the default filters?

Even with uBlock Origin it is quite difficult for the average user to resolve some problematic websites with cookie consent.

**Comment by gorhill** [comment]
> some exceptions to the default filters

What does that mean in practice? Not sure I understand what you mean by "exceptions" concretely.

**Comment by krystian3w** [comment]
> That won't be part of uBO Lite, otherwise it's not going to be Lite anymore. For this sort of functionality, that is uBO itself. There is no point using the Lite version if you want everything uBO itself already has.

But chrome will eventually say basta to MV2 and uBo will end for it if only in e.g. 2030 as they will find that 2/3 of MV2 postlats will no longer be able to be implemented in MV3 anyway.

**Comment by SampeiNihira** [comment]
> > some exceptions to the default filters
> 
> What does that mean in practice? Not sure I understand what you mean by "exceptions" concretely.

Check out this website:

https://ita.xhamster.com/photos

With full filtering no cookie warning but missing sidebar on right to scroll down the page:

![0](https://github.com/uBlockOrigin/uBOL-issues/assets/44166263/1bb26ef0-ddf3-48c8-8a19-4554e6fe0344)


With optimal filtering there is cookie warning you can reject cookies and then the website is fully usable:

![0a](https://github.com/uBlockOrigin/uBOL-issues/assets/44166263/587399e7-092a-4f5c-9ff3-9268346ae2d8)

**Comment by krystian3w** [comment]
We have file to repair bugs specific for uBo Lite only:

https://github.com/uBlockOrigin/uAssets/blob/master/filters/ubol-filters.txt

So stock bugs can be addressed their.

**Comment by gorhill** [comment]
I get the same issue in uBO, it's a filter issue, and should be reported like any other filter issue in uBO.

**Comment by dportvine** [comment]
> > > some exceptions to the default filters
> > 
> > 
> > What does that mean in practice? Not sure I understand what you mean by "exceptions" concretely.
> 
> Check out this website:
> 
> `https://ita.xhamster.com/photos`
> 
> With full filtering no cookie warning but missing sidebar on right to scroll down the page:
> 
> https://github.com/uBlockOrigin/uBOL-issues/assets/44166263/1bb26ef0-ddf3-48c8-8a19-4554e6fe0344
> 
> With optimal filtering there is cookie warning you can reject cookies and then the website is fully usable:
> 
> https://github.com/uBlockOrigin/uBOL-issues/assets/44166263/587399e7-092a-4f5c-9ff3-9268346ae2d8

I can reproduce with uBO 1.50.0 VPN(Netherlands), Google Chrome.
`##.cookies-modal:not(body):not(html)` ~> **EasyList – Cookie Notices**

<details>
<summary>Screen</summary>

![2023-06-08_220516](https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/db2610d6-3cfe-4858-b139-23acf9394181)
</details>

@ryanbr

**Comment by Yuki2718** [comment]
If less people report, lists don't improve and will cause more problems. User with an ability to fix problems simply **should** report, which is a [trivial contribution](https://twitter.com/gorhill/status/1432712384624345091) virtually everyone can do.

**Comment by SampeiNihira** [comment]
Trivial?
See how trivial it is to report.

https://github.com/AdguardTeam/AdguardFilters/issues/152486

Many users let it go,and they do well.

**Comment by krystian3w** [comment]
You can always inquire about a full-time position at AdGuard so that you can cast off your typical Japanese job.

Unless AdGuard offers starvation wages and your many years of work in one company gives you several times more.

Aside from the fact that Japanese grandparents take a bad look when someone has several companies on their resume.

**Comment by krystian3w** [comment]
If uBo Lite never gets a field for custom rules or filters lists then probably Chrome (Not Brave/Vivaldi/Opera) users in 2030 will be gobbled up by AdGuard MV3 or they will fall back on AdBlock/Adblock Plus if porting uBO MV2 will continue to be impossible.
