### ISSUE TITLE
https://45.141.56.28/800-bullets-2002-jf/
I see video ads with firefox android and banner

### ISSUE THREAD

**Issue by Jokopentil** [uBlockOrigin/uBOL-issues#53]
![20230625_165453_rmscr.jpg](https://github.com/uBlockOrigin/uBOL-issues/assets/114223791/db7ecf51-a453-40ff-8f63-fea72c1012a9)

![20230629_221738_rmscr.jpg](https://github.com/uBlockOrigin/uBOL-issues/assets/114223791/41137f7f-0730-424f-b44c-14a0dd474d7c)

**Comment by gorhill** [comment]
uBO Lite is not available on Firefox, you are probably using uBO. To report such issue with uBO use the [_chat_ icon in the popup panel](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools).

**Comment by Jokopentil** [comment]
![20230630_175321_rmscr.jpg](https://github.com/uBlockOrigin/uBOL-issues/assets/114223791/570cc9c0-8d9b-49a3-ae78-94914b8eade0)

With kiwi browser can'ot block ads video
I was updated filter
