### ISSUE TITLE
Language specific filters are not applied after reloading

### ISSUE THREAD

**Issue by netl0tuz** [uBlockOrigin/uBOL-issues#56]
### Description
Language specific filters are not applied after reloading extension.

### Steps to Reproduce
1. applying any language filter list
2. reloading extension page or restarting browser

### Configuration
```
Brave : 1.52.130 (114.0.1823.67)
Edge :  114.0.1823.67
uBlock Origin Lite : 1.0.23.6195
```

**Comment by gorhill** [comment]
Unable to reproduce using Chromium 114.0.5735.198.

**Comment by gorhill** [comment]
What do you mean by "not applied"?

**Comment by netl0tuz** [comment]
> What do you mean by "not applied"?

after selecting any language filter list and reloading page they just get removed

  
![Screenshot (1)](https://github.com/uBlockOrigin/uBOL-issues/assets/77051824/55b7cf3e-8843-4923-bb92-205319d16224)

![Screenshot (2)](https://github.com/uBlockOrigin/uBOL-issues/assets/77051824/ecdc5fdf-50f4-4eda-944d-7c53ebd9ec8f)

i am also using windows 11 , if it's connected to issue of not being reproducible anyhow

**Comment by gorhill** [comment]
OK I see the problem: you can't subscribe to more than 10 filter lists, it's an MV3 limitations. I will need to adjust the user interface to reflect this.

**Comment by netl0tuz** [comment]
since it's an MV3 limitation and unchangeable, I'm going to close the problem.

**Comment by gorhill** [comment]
I need to disabllow selecting more than 10 lists in the user interface.

**Comment by gwarser** [comment]
@MasterKia should work automatically https://github.com/gorhill/uBlock/commit/634fdde465115bf0c4938f3d9faf74eac85ae674#diff-63974c0a8dd44b163b9d3bdcfa6d67eb43772a9a4fc3164c51fdb1d6f1dde07cR194
