### ISSUE TITLE
uploadrar.com

### ISSUE THREAD

**Issue by dportvine** [uBlockOrigin/uBOL-issues#58]
`https://uploadrar.com/n681tbsxlzfy` adblock detected

<details>
<summary>Screen</summary>

https://github.com/uBlockOrigin/uBOL-issues/assets/111344219/5d89245c-c786-4ab4-83e3-1fb083bf3f8c
</details>

uBlock Origin Lite 1.0.23.7095
Google Chrome 114.0.5735.199
Windows 10 22H2 x64

**Comment by gorhill** [comment]
Works fine if you downgrade to _Optimal_ though.

**Comment by gorhill** [comment]
This is caused by uBOL not properly compiling generic cosmetic exception filters.

**Comment by dportvine** [comment]
I use **Complete** mode to hide the cookie message.
