### ISSUE TITLE
Brave uBO lite not working

### ISSUE THREAD

**Issue by GitStudying** [uBlockOrigin/uBOL-issues#59]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] using a new, unmodified browser profile.

### Description

I use Brave which is a browser based on Chromium. I know that brave has sort of build in adblock, but for Youtube specifically this causes issues mostly that the resolution  does not stay at 1080p. As when I disable Braves adblock it does stay at 1080p or at what I set. So I installed uBlock origin lite and wanted to turn it on so set the option to full filter mode. When I tried this the option did not stick so on refresh none of the modes are set again. Also if I click on the extension next to the address bar the UI is just a dark grey pane/background with nothing in it. I granted it all access inside of extension properties so that should not be the problem.
To be clear the issue is not specifically related to Youtube however to reason why I want another adblock I added that to this issue.

### A specific URL where the issue occurs.

everywhere

### Steps to Reproduce

1. Install Brave
2. Install uBlock origin lite
3. Grant all access to the extension
4. Try to enable or set filtermode

### Expected behavior

Filter options are saved and working ad block on sites. As well as working gui from extension.

### Actual behavior

Broken interface, no adblock and no way to set filter options.

### Configuration

Brave browser on Windows 11

**Comment by gorhill** [comment]
I install Brave 1.52.130 and all is working fine on my side, unable to reproduce any issue with uBO Lite.

**Comment by GitStudying** [comment]
I am really confused and I think it is working now, the interface is showing up and I can select the filters I want as well as setting filter mode. So I think it fixed itself, at least for now it seems fixed.

**Comment by zmyxpt** [comment]
Same, but I can reproduce.

1. install brave browser, in my case, version is brave 1.57.47
2. install uBO lite from extension store
3. exit brave browser
4. start brave browser, now uBO lite not working, F12 console give an error

other info:

chromium + uBO = work
chromium + uBO lite = work
brave + uBO = work
brave + uBO lite = not work
