### ISSUE TITLE
onlytech.com, dreamdth.com

### ISSUE THREAD

**Issue by hj-collab** [uBlockOrigin/uBOL-issues#62]
uBOL is not able to bypass anti-adblock. Latest uBOL version on Google Chrome.

**Comment by gorhill** [comment]
I don't see any anti-blocker at these sites. You will have to be more generous with details to reproduce. Closing as _invalid_ until you provide all steps for others to reproduce.

**Comment by gorhill** [comment]
What blocking level are you using? The anti-blocker goes away when I raise the blocking level for the site to _Optimal_ or _Complete_.

**Comment by gorhill** [comment]
> I was on Basic level of ad-blocking

You can raise for either just the site itself from the popup menu, or raise for all sites from the dashboard.
