### ISSUE TITLE
How to block Outbrain and Taboola content?

### ISSUE THREAD

**Issue by OsamaAbbas** [uBlockOrigin/uBOL-issues#7]
Hello,

Thank you for the great tool!

I was wondering how to block Outbrain and Taboola content. I'm using uBO Lite right now. I don't remember seeing these ads when I was using the uBlock Origin addon.

Is there any way to add custom filters in uBO Lite?

Here is the options screen on my Chrome:

![image](https://user-images.githubusercontent.com/3346502/195282142-6a14acb1-4764-4f05-8b4c-4698f3304f6f.png)

**Comment by OsamaAbbas** [comment]
And here is a link that shows the offending content:

https://edition.cnn.com/videos/business/2022/06/23/nightcap-crypto-clip-orig.cnn

![image](https://user-images.githubusercontent.com/3346502/195282359-85352ceb-c6c4-4a0a-ac4d-0bd0c44f8fd2.png)

**Comment by gorhill** [comment]
Taboola and Outbrain should be blocked by default. I am not able to see these at the link you provided.

**Comment by gorhill** [comment]
See if you get the issue with the latest release, which is currently pending approval in the Chrome Web Store. The filter blocking Outbrain is `||outbrain.com^$3p` and it's being blocked on my side.

**Comment by mapx-** [comment]
in unbreak I added time ago some filters to unbreak a section, whitelisting some outbrain stuff.
The strange thing I get outbrain stuff now only in firefox not in chrome

```
! unlock Watch It section cnn.com
@@||outbrain.com^$script,domain=cnn.com
@@||outbrainimg.com^$image,domain=cnn.com
cnn.com##.OB_AR_2
cnn.com##.m-outbrain
cnn.com##.ob-cards
cnn.com##.ob-widget
```

I added 2 minutes ago the last 2 filters

**Comment by OsamaAbbas** [comment]
Thank you for the quick response.

OK. I will test the same link on another PC. And I will check with the latest version as well.

On my main machine though (Linux mint, with the latest chrome), the issue is definitely there.

Is there any way (or will there be any way) to add custom filter or block specific elements with uBO Lite?

**Comment by gorhill** [comment]
On my side there is a iframe containing the Outbrain stuff, it's being wholly blocked by `||outbrain.com^$3p` and as a result it's being collapsed by the browser.

**Comment by OsamaAbbas** [comment]
I have created another profile on the same Linux machine, and the outbrain content is blocked successfully. The outbrain script `https://widgets.outbrain.com/outbrain.js` is not blocked as well.

Thank you for your help. I will close this issue as the problem is in my default profile. (hopefully cleaning it will solve the issue).

My final question is this:
> Is there any way (or will there be any way) to add custom filters or block specific elements with uBO Lite?

**Comment by gorhill** [comment]
Ok that's odd, now I get the Outbrain ads, and they are not longer served from within an iframe.

@mapx- We really shouldn't have `@@||outbrain.com^$script,domain=cnn.com`, those Watch It sections are just a trick from Outbrain to bypass blockers, there is no value to these and they it was meant to be blocked by default. People who complain of breakage will have to use custom filters to bypass the blocking.

**Comment by gorhill** [comment]
> Is there any way (or will there be any way) to add custom filters or block specific elements with uBO Lite?

Not possible, and it's unclear whether it will be possible in some future given that a self-imposed restriction is to be entirely declarative. For network filtering this is probably possible to have custom filters, but for cosmetic filtering, there would need to be a new API in the browser to allow for this.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14855
