### ISSUE TITLE
uBlock Origin Lite default filter breaks pushbullet extension

### ISSUE THREAD

**Issue by tankaras** [uBlockOrigin/uBOL-issues#8]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

Pushbullet breaks when Default filter is selected
> Ads, Trackers, Miners, And More

...................................

P.S I have tested original uBlock Origin extension and it does not exhibit this behavior.

### A specific URL where the issue occurs.

`https://www.pushbullet.com`

### Steps to Reproduce

1. Install pushbullet extension and login with account
2. Install ublock lite extension
3. Select default filter list if not selected
4. Test sending/receiving a push message

### Expected behavior

Pushbullet extension to work as normal

### Actual behavior

1. Sending message/link fails 
2. Extension doesn't receive messages from other pb clients

### uBO version

uBlock Origin Lite 0.1.22.9305

### Browser name and version

Ungoogled chromium 106.0.5249.91

### Operating System and version

Arch Linux with kernel 6.0.0

**Comment by mapx-** [comment]
update to the last version `uBlock Origin Lite 0.1.22.10106` and test if still happens

**Comment by tankaras** [comment]
> update to the last version `uBlock Origin Lite 0.1.22.10106` and test if still happens

Just updated. No dice.

**Comment by mapx-** [comment]
Inspect on pb extension => in console issues on `static.pushbullet.com ...`

EasyPrivacy has a filter => `||pushbullet.com^$third-party`

I downloaded uBOL to installed it manually as unpacked extension
https://github.com/gorhill/uBlock/releases/tag/uBOLite_0.1.22.10106

Then I edited `default.json` file removing `"pushbullet.com",` , I updated uBOL (extensions panel) to get the new `default.json` version and this way seems the pb extension works correctly.

Why uBO has no issues with the same filter ?

@gorhill

**Comment by gorhill** [comment]
Is anything blocked by uBO for `pushbullet.com`? If not, what is the context of network requests to `pushbullet.com`?

**Comment by mapx-** [comment]
in uBO I get nothing in the extension console

in uBOL

```
d3d92f6609934655e5b8c4d79cef05d1bfd6caa1f0bdf89cbf78118fb46c9c6a:1          GET https://static.pushbullet.com/google-user/d3d92f6609934655e5b8c4d79cef05d1bfd6caa1f0bdf89cbf78118fb46c9c6a net::ERR_BLOCKED_BY_CLIENT
Image (async)
createStreamRow @ panel-messaging.js:137
(anonymous) @ panel-messaging-push.js:314
setUpPushStreams @ panel-messaging-push.js:287
pushesLocalsChangedListener @ panel-messaging-push.js:68
onFocusChanged @ panel-messaging.js:12
(anonymous) @ page.js:8
ec9e31da85bd6db35f40f1e23833e05b7a8fa4942ff372c054efc21739f534fb:1          GET https://static.pushbullet.com/google-user/ec9e31da85bd6db35f40f1e23833e05b7a8fa4942ff372c054efc21739f534fb net::ERR_BLOCKED_BY_CLIENT
Image (async)
(anonymous) @ chat-push.js:431
(anonymous) @ chat-push.js:231
renderPushChunks @ chat-push.js:226
drawPushChat @ chat-push.js:43
updatePushChat @ chat-push.js:5
pushesLocalsChangedListener @ panel-messaging-push.js:77
onFocusChanged @ panel-messaging.js:12
(anonymous) @ page.js:8
```

**Comment by mapx-** [comment]
the network tab:

![image](https://user-images.githubusercontent.com/10303732/195341006-a0630343-9421-4cd0-8cff-04d1c330f10b.png)

**Comment by gorhill** [comment]
> Inspect on pb extension

Ok I understand. With MV3 API, uBOL is allowed to interfere with another extension's network requests, which is quite unexpected and it does appear to be a bug in the API. In MV2, extensions are not allowed to read/modify network requests made by other extensions.

**Comment by mapx-** [comment]
In this case is there a special context (identifying an extension) just to understand if it's impacting another extension ?

**Comment by gorhill** [comment]
The initiator is the `chrome-extension://` protocol, so I wonder if I can exclude uBOL using an allowAll rule, I will have to experiment.

**Comment by mapx-** [comment]
I've notified Simeon Vincent on slack

**Comment by gorhill** [comment]
I can't seem to be able to fix this with a rule, so we will need a `ubol-filters.txt`list to create exceptions for these cases for the time being.

**Comment by gorhill** [comment]
Why reopen?

**Comment by tankaras** [comment]
Same anomaly has cropped up again with the newly added blocklists, namely

`EasyList – Annoyances`
