### ISSUE TITLE
Add more detailed descriptions on MV3 filtering modes

### ISSUE THREAD

**Issue by mon-jai** [uBlockOrigin/uBOL-issues#9]
### Prerequisites

- [X] I verified that this is not a filter list issue. Report any issues with filter lists or broken website functionality in the [uAssets issue tracker](https://github.com/uBlockOrigin/uAssets/issues).
- [X] This is not a support issue or a question. For any support, questions or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] The issue is not present after disabling uBO in the browser.
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I am reporting is not normal behavior.

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

The [uBOLite_0.1.22.10106 release note](https://github.com/gorhill/uBlock/releases/tag/uBOLite_0.1.22.10106) explained what does "complete mode" do, and how to choose between filtering modes very clearly.

> Recommendation: the optimal mode is the suggested one, and complete mode should be used only on websites for which it has a positive effect -- typically this mode will take care of placeholders left behind on a page, when these placeholders have not been taken care by specific cosmetic filters of optimal mode.

It would be better if we
1. Include the above paragraph in the dashboard
2. Label Optimal mode as recommended (e.g. `Optimal (recommended)`)

### A specific URL where the issue occurs.

Dashboard

### Steps to Reproduce

1. Open dashboard

### Expected behavior

We should explain more about choosing filtering modes in the dashboard.

### Actual behavior

Users are unclear about which mode should they choose for "default filtering mode" and "per-website filtering mode".

### uBO version

uBlock Origin Lite 0.1.22.10135

### Browser name and version

Chrome Version 106.0.5249.119

### Operating System and version

Windows 11

**Comment by gorhill** [comment]
"Optimal" is defined as "most desirable or satisfactory", so it's self-explanatory.

**Comment by gorhill** [comment]
> Include the above paragraph in the dashboard

I prefer not, I may very well change my mind about this, and especially if I find people make it more than what it is I will readily remove it in short order. My only concern was the added memory usage to web pages, which is currently completely out of my control with MV3. If this proves to be the new normal with regard to Chromium extension, I will actually remove the paragraph from the welcome section.
